version: '2'
services:
  blockchainservice-app:
    image: blockchainservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://blockchainservice-mariadb:3306/blockchainservice
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  blockchainservice-mariadb:
    extends:
      file: mariadb.yml
      service: blockchainservice-mariadb
